//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eCommerceEntities : DbContext
    {
        public eCommerceEntities()
            : base("name=eCommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<deposito> depositoes { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<pago> pagoes { get; set; }
        public virtual DbSet<plastico> plasticoes { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<producto_proveedor> producto_proveedor { get; set; }
        public virtual DbSet<proveedor> proveedors { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
        public virtual DbSet<venta_producto> venta_producto { get; set; }
    }
}
