//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pago()
        {
            this.ventas = new HashSet<venta>();
        }
    
        public int id_pago { get; set; }
        public string tipo_pago { get; set; }
        public double monto { get; set; }
        public Nullable<int> id_deposito { get; set; }
        public Nullable<int> id_plastico { get; set; }
        public Nullable<int> id_factura { get; set; }
    
        public virtual deposito deposito { get; set; }
        public virtual factura factura { get; set; }
        public virtual plastico plastico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> ventas { get; set; }
    }
}
