//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class plastico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plastico()
        {
            this.pagoes = new HashSet<pago>();
        }
    
        public int id_tarjeta { get; set; }
        public string tipo_tarjeta { get; set; }
        public string proveedor_tarjeta { get; set; }
        public string nombre_titular { get; set; }
        public int numero_tarjeta { get; set; }
        public string mes_exp { get; set; }
        public int ano_exp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago> pagoes { get; set; }
    }
}
