//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_proveedor
    {
        public int prod_prov { get; set; }
        public int id_producto { get; set; }
        public int id_proveedor { get; set; }
        public double precio_unitario { get; set; }
        public int cantidad_minima { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
